name: Scan Code
on:
  push:
    branches: ["dev", "prod"]
jobs:
  build:
    name: Scan Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          # security-checks: 'vuln,secret,config'
          ignore-unfixed: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'


      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'code'
          token: ${{ secrets.GITHUB_TOKEN }}